/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 52K7GWKZcCo6aFrZqDHdPd
// Component: a_-Wr366gy-6

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 52K7GWKZcCo6aFrZqDHdPd/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 52K7GWKZcCo6aFrZqDHdPd/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 52K7GWKZcCo6aFrZqDHdPd/projectcss
import sty from "./PlasmicMenuIcon.module.css"; // plasmic-import: a_-Wr366gy-6/css

import StickynoteIcon from "./icons/PlasmicIcon__Stickynote"; // plasmic-import: bmI1i9fk2myI/icon
import Icon10Icon from "./icons/PlasmicIcon__Icon10"; // plasmic-import: Uavh4OrJu1na/icon
import Icon11Icon from "./icons/PlasmicIcon__Icon11"; // plasmic-import: Uc12jN-Ph2ag/icon
import Icon12Icon from "./icons/PlasmicIcon__Icon12"; // plasmic-import: bKEa5KWQXLij/icon

createPlasmicElementProxy;

export type PlasmicMenuIcon__VariantMembers = {
  select: "select";
  icons: "notebook" | "target" | "chart" | "history";
};
export type PlasmicMenuIcon__VariantsArgs = {
  select?: SingleBooleanChoiceArg<"select">;
  icons?: SingleChoiceArg<"notebook" | "target" | "chart" | "history">;
};
type VariantPropType = keyof PlasmicMenuIcon__VariantsArgs;
export const PlasmicMenuIcon__VariantProps = new Array<VariantPropType>(
  "select",
  "icons"
);

export type PlasmicMenuIcon__ArgsType = {};
type ArgPropType = keyof PlasmicMenuIcon__ArgsType;
export const PlasmicMenuIcon__ArgProps = new Array<ArgPropType>();

export type PlasmicMenuIcon__OverridesType = {
  root?: Flex__<"svg">;
};

export interface DefaultMenuIconProps {
  select?: SingleBooleanChoiceArg<"select">;
  icons?: SingleChoiceArg<"notebook" | "target" | "chart" | "history">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicMenuIcon__RenderFunc(props: {
  variants: PlasmicMenuIcon__VariantsArgs;
  args: PlasmicMenuIcon__ArgsType;
  overrides: PlasmicMenuIcon__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "select",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.select
      },
      {
        path: "icons",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.icons
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <PlasmicIcon__
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      PlasmicIconType={
        hasVariant($state, "icons", "history")
          ? Icon12Icon
          : hasVariant($state, "icons", "chart")
          ? Icon11Icon
          : hasVariant($state, "icons", "target")
          ? Icon10Icon
          : StickynoteIcon
      }
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        {
          [sty.rooticons_chart]: hasVariant($state, "icons", "chart"),
          [sty.rooticons_history]: hasVariant($state, "icons", "history"),
          [sty.rooticons_notebook]: hasVariant($state, "icons", "notebook"),
          [sty.rooticons_target]: hasVariant($state, "icons", "target"),
          [sty.rootselect]: hasVariant($state, "select", "select")
        }
      )}
      role={"img"}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMenuIcon__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMenuIcon__VariantsArgs;
    args?: PlasmicMenuIcon__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicMenuIcon__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMenuIcon__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMenuIcon__ArgProps,
          internalVariantPropNames: PlasmicMenuIcon__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMenuIcon__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMenuIcon";
  } else {
    func.displayName = `PlasmicMenuIcon.${nodeName}`;
  }
  return func;
}

export const PlasmicMenuIcon = Object.assign(
  // Top-level PlasmicMenuIcon renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicMenuIcon
    internalVariantProps: PlasmicMenuIcon__VariantProps,
    internalArgProps: PlasmicMenuIcon__ArgProps
  }
);

export default PlasmicMenuIcon;
/* prettier-ignore-end */
