/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 52K7GWKZcCo6aFrZqDHdPd

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsryZbY87Yhrv } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: RyZbY87yhrv_/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsryZbY87Yhrv
});
