/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 52K7GWKZcCo6aFrZqDHdPd
// Component: U-Uxn7aboBAF

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import MenuItem2 from "../../MenuItem2"; // plasmic-import: fmoPxpQpYqgz/component
import Category from "../../Category"; // plasmic-import: 4pVr3gxDVuEL/component
import HeaderTable from "../../HeaderTable"; // plasmic-import: vK-7aGybC8A8/component
import ItemTable from "../../ItemTable"; // plasmic-import: ElZgbQ-jdSUQ/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 52K7GWKZcCo6aFrZqDHdPd/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 52K7GWKZcCo6aFrZqDHdPd/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 52K7GWKZcCo6aFrZqDHdPd/projectcss
import sty from "./PlasmicSideBar.module.css"; // plasmic-import: U-Uxn7aboBAF/css

import Line2Icon from "./icons/PlasmicIcon__Line2"; // plasmic-import: Z7x-Pgf_Ho8C/icon
import LogoutIcon from "./icons/PlasmicIcon__Logout"; // plasmic-import: nVkh9L8By6os/icon
import SearchNormalIcon from "./icons/PlasmicIcon__SearchNormal"; // plasmic-import: cyu4pwsbyiQT/icon
import AddIcon from "./icons/PlasmicIcon__Add"; // plasmic-import: IReWwvKfiRgI/icon
import ArrowDownIcon from "./icons/PlasmicIcon__ArrowDown"; // plasmic-import: 74C3eG3qZkkc/icon

createPlasmicElementProxy;

export type PlasmicSideBar__VariantMembers = {};
export type PlasmicSideBar__VariantsArgs = {};
type VariantPropType = keyof PlasmicSideBar__VariantsArgs;
export const PlasmicSideBar__VariantProps = new Array<VariantPropType>();

export type PlasmicSideBar__ArgsType = {};
type ArgPropType = keyof PlasmicSideBar__ArgsType;
export const PlasmicSideBar__ArgProps = new Array<ArgPropType>();

export type PlasmicSideBar__OverridesType = {
  root?: Flex__<"div">;
  frame11?: Flex__<"div">;
  frame14?: Flex__<"div">;
  logo?: Flex__<"div">;
  frame12?: Flex__<"div">;
  menuItem2?: Flex__<typeof MenuItem2>;
  frame13?: Flex__<"div">;
  frame6?: Flex__<"div">;
  frame8?: Flex__<"div">;
  frame10?: Flex__<"div">;
  frame7?: Flex__<"div">;
  vuesaxLinearLogout?: Flex__<"div">;
  vuesaxLinearLogout2?: Flex__<"div">;
  frame19?: Flex__<"div">;
  frame20?: Flex__<"div">;
  vuesaxLinearSearchNormal?: Flex__<"div">;
  vuesaxLinearSearchNormal2?: Flex__<"div">;
  frame18?: Flex__<"div">;
  frame9?: Flex__<"div">;
  vuesaxLinearAdd?: Flex__<"div">;
  vuesaxLinearAdd2?: Flex__<"div">;
  frame17?: Flex__<"div">;
  frame16?: Flex__<"div">;
  frame15?: Flex__<"div">;
  vuesaxBoldArrowDown?: Flex__<"div">;
  vuesaxBoldArrowDown2?: Flex__<"div">;
  empty1?: Flex__<"div">;
  frame21?: Flex__<"div">;
  vuesaxLinearAdd3?: Flex__<"div">;
  vuesaxLinearAdd4?: Flex__<"div">;
  category?: Flex__<typeof Category>;
  frame47?: Flex__<"div">;
  headerTable?: Flex__<typeof HeaderTable>;
  frame46?: Flex__<"div">;
  itemTable?: Flex__<typeof ItemTable>;
};

export interface DefaultSideBarProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSideBar__RenderFunc(props: {
  variants: PlasmicSideBar__VariantsArgs;
  args: PlasmicSideBar__ArgsType;
  overrides: PlasmicSideBar__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "menu",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => [
          {
            id: "journal",
            label_fa: "\u0698\u0648\u0631\u0646\u0627\u0644",
            label_en: "Journal",
            icon: "notebook",
            route: "/journal"
          },
          {
            id: "strategy",
            label_fa: "\u0627\u0633\u062a\u0631\u0627\u062a\u0698\u06cc",
            label_en: "Strategy",
            icon: "target",
            route: "/strategy"
          },
          {
            id: "analysis",
            label_fa: "\u062a\u062d\u0644\u06cc\u0644",
            label_en: "Analysis",
            icon: "chart",
            route: "/analysis"
          },
          {
            id: "backtest",
            label_fa: "\u0628\u06a9\u200c\u062a\u0633\u062a",
            label_en: "Backtest",
            icon: "history",
            route: "/backtest"
          }
        ]
      },
      {
        path: "item",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"frame11"}
        data-plasmic-override={overrides.frame11}
        className={classNames(projectcss.all, sty.frame11)}
      >
        <div
          data-plasmic-name={"frame14"}
          data-plasmic-override={overrides.frame14}
          className={classNames(projectcss.all, sty.frame14)}
        >
          <div
            data-plasmic-name={"logo"}
            data-plasmic-override={overrides.logo}
            className={classNames(projectcss.all, sty.logo)}
          >
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__qae28)}
              displayHeight={"26.270618438720703px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"39.999961853027344px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/website_starter/images/logo.svg",
                fullWidth: 39.999961853027344,
                fullHeight: 26.270618438720703,
                aspectRatio: undefined
              }}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__oqYiy
              )}
            >
              {"Trading Map"}
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___8OLty)}>
            <Line2Icon
              className={classNames(projectcss.all, sty.svg__qOyLu)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"frame12"}
            data-plasmic-override={overrides.frame12}
            className={classNames(projectcss.all, sty.frame12)}
          >
            {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
              (() => {
                try {
                  return $state.menu;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return [];
                  }
                  throw e;
                }
              })()
            ).map((__plasmic_item_0, __plasmic_idx_0) => {
              const currentItem = __plasmic_item_0;
              const currentIndex = __plasmic_idx_0;
              return (
                <MenuItem2
                  data-plasmic-name={"menuItem2"}
                  data-plasmic-override={overrides.menuItem2}
                  className={classNames("__wab_instance", sty.menuItem2)}
                  icon={(() => {
                    try {
                      return currentItem.icon;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                  key={currentIndex}
                  onClick={async event => {
                    const $steps = {};

                    $steps["updateItem"] = true
                      ? (() => {
                          const actionArgs = {
                            variable: {
                              objRoot: $state,
                              variablePath: ["item"]
                            },
                            operation: 0,
                            value: currentItem.id
                          };
                          return (({
                            variable,
                            value,
                            startIndex,
                            deleteCount
                          }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;

                            $stateSet(objRoot, variablePath, value);
                            return value;
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["updateItem"] != null &&
                      typeof $steps["updateItem"] === "object" &&
                      typeof $steps["updateItem"].then === "function"
                    ) {
                      $steps["updateItem"] = await $steps["updateItem"];
                    }
                  }}
                  select={(() => {
                    try {
                      return $state.item == currentItem.id;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return [];
                      }
                      throw e;
                    }
                  })()}
                  text={(() => {
                    try {
                      return currentItem.label_en;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                />
              );
            })}
          </div>
        </div>
        <div
          data-plasmic-name={"frame13"}
          data-plasmic-override={overrides.frame13}
          className={classNames(projectcss.all, sty.frame13)}
        >
          <div
            data-plasmic-name={"frame6"}
            data-plasmic-override={overrides.frame6}
            className={classNames(projectcss.all, sty.frame6)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ydSKe
              )}
            >
              {"Upgrade To Pro \ud83d\udd25"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ceqrz
              )}
            >
              {"Get 1 mounth free and unlock all Pro features"}
            </div>
            <div
              data-plasmic-name={"frame8"}
              data-plasmic-override={overrides.frame8}
              className={classNames(projectcss.all, sty.frame8)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__d2NeX
                )}
              >
                {"Upgrade"}
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"frame10"}
            data-plasmic-override={overrides.frame10}
            className={classNames(projectcss.all, sty.frame10)}
          >
            <div
              data-plasmic-name={"frame7"}
              data-plasmic-override={overrides.frame7}
              className={classNames(projectcss.all, sty.frame7)}
            >
              <div
                data-plasmic-name={"vuesaxLinearLogout"}
                data-plasmic-override={overrides.vuesaxLinearLogout}
                className={classNames(projectcss.all, sty.vuesaxLinearLogout)}
              >
                <div
                  data-plasmic-name={"vuesaxLinearLogout2"}
                  data-plasmic-override={overrides.vuesaxLinearLogout2}
                  className={classNames(
                    projectcss.all,
                    sty.vuesaxLinearLogout2
                  )}
                >
                  <LogoutIcon
                    className={classNames(projectcss.all, sty.svg___7UbC8)}
                    role={"img"}
                  />
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__lgCPl
                )}
              >
                {"Log Out"}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__z65Hk)}>
        <div
          data-plasmic-name={"frame19"}
          data-plasmic-override={overrides.frame19}
          className={classNames(projectcss.all, sty.frame19)}
        >
          <div
            data-plasmic-name={"frame20"}
            data-plasmic-override={overrides.frame20}
            className={classNames(projectcss.all, sty.frame20)}
          >
            <div
              data-plasmic-name={"vuesaxLinearSearchNormal"}
              data-plasmic-override={overrides.vuesaxLinearSearchNormal}
              className={classNames(
                projectcss.all,
                sty.vuesaxLinearSearchNormal
              )}
            >
              <div
                data-plasmic-name={"vuesaxLinearSearchNormal2"}
                data-plasmic-override={overrides.vuesaxLinearSearchNormal2}
                className={classNames(
                  projectcss.all,
                  sty.vuesaxLinearSearchNormal2
                )}
              >
                <SearchNormalIcon
                  className={classNames(projectcss.all, sty.svg__kYnHc)}
                  role={"img"}
                />
              </div>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ryNlU
              )}
            >
              {"Search or type a command"}
            </div>
          </div>
          <div
            data-plasmic-name={"frame18"}
            data-plasmic-override={overrides.frame18}
            className={classNames(projectcss.all, sty.frame18)}
          >
            <div
              data-plasmic-name={"frame9"}
              data-plasmic-override={overrides.frame9}
              className={classNames(projectcss.all, sty.frame9)}
            >
              <div
                data-plasmic-name={"vuesaxLinearAdd"}
                data-plasmic-override={overrides.vuesaxLinearAdd}
                className={classNames(projectcss.all, sty.vuesaxLinearAdd)}
              >
                <div
                  data-plasmic-name={"vuesaxLinearAdd2"}
                  data-plasmic-override={overrides.vuesaxLinearAdd2}
                  className={classNames(projectcss.all, sty.vuesaxLinearAdd2)}
                >
                  <AddIcon
                    className={classNames(projectcss.all, sty.svg__m4O)}
                    role={"img"}
                  />
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__u1ScF
                )}
              >
                {"Create"}
              </div>
            </div>
            <div
              data-plasmic-name={"frame17"}
              data-plasmic-override={overrides.frame17}
              className={classNames(projectcss.all, sty.frame17)}
            >
              <div
                data-plasmic-name={"frame16"}
                data-plasmic-override={overrides.frame16}
                className={classNames(projectcss.all, sty.frame16)}
              >
                <div
                  data-plasmic-name={"frame15"}
                  data-plasmic-override={overrides.frame15}
                  className={classNames(projectcss.all, sty.frame15)}
                >
                  <div
                    data-plasmic-name={"vuesaxBoldArrowDown"}
                    data-plasmic-override={overrides.vuesaxBoldArrowDown}
                    className={classNames(
                      projectcss.all,
                      sty.vuesaxBoldArrowDown
                    )}
                  >
                    <div
                      data-plasmic-name={"vuesaxBoldArrowDown2"}
                      data-plasmic-override={overrides.vuesaxBoldArrowDown2}
                      className={classNames(
                        projectcss.all,
                        sty.vuesaxBoldArrowDown2
                      )}
                    >
                      <ArrowDownIcon
                        className={classNames(projectcss.all, sty.svg__dIssA)}
                        role={"img"}
                      />
                    </div>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ygbwx
                    )}
                  >
                    {"Nokindow"}
                  </div>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3YcY0
                  )}
                >
                  {"Nokindow@gmail.com"}
                </div>
              </div>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__scsZ7)}
                displayHeight={"48px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"48px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/website_starter/images/ellipse2.svg",
                  fullWidth: 48,
                  fullHeight: 48,
                  aspectRatio: undefined
                }}
              />
            </div>
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__njSxs)}>
          <div
            data-plasmic-name={"empty1"}
            data-plasmic-override={overrides.empty1}
            className={classNames(projectcss.all, sty.empty1)}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___4BrGt
            )}
          >
            {"This section is empty"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__kC6Cx
            )}
          >
            {"Click Create to display the information"}
          </div>
          <div
            data-plasmic-name={"frame21"}
            data-plasmic-override={overrides.frame21}
            className={classNames(projectcss.all, sty.frame21)}
          >
            <div
              data-plasmic-name={"vuesaxLinearAdd3"}
              data-plasmic-override={overrides.vuesaxLinearAdd3}
              className={classNames(projectcss.all, sty.vuesaxLinearAdd3)}
            >
              <div
                data-plasmic-name={"vuesaxLinearAdd4"}
                data-plasmic-override={overrides.vuesaxLinearAdd4}
                className={classNames(projectcss.all, sty.vuesaxLinearAdd4)}
              >
                <AddIcon
                  className={classNames(projectcss.all, sty.svg__n92Wk)}
                  role={"img"}
                />
              </div>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__l0Uh
              )}
            >
              {"Create"}
            </div>
          </div>
          <Category
            data-plasmic-name={"category"}
            data-plasmic-override={overrides.category}
            className={classNames("__wab_instance", sty.category)}
          />

          <div
            data-plasmic-name={"frame47"}
            data-plasmic-override={overrides.frame47}
            className={classNames(projectcss.all, sty.frame47)}
          >
            <HeaderTable
              data-plasmic-name={"headerTable"}
              data-plasmic-override={overrides.headerTable}
              className={classNames("__wab_instance", sty.headerTable)}
            />

            <div
              data-plasmic-name={"frame46"}
              data-plasmic-override={overrides.frame46}
              className={classNames(projectcss.all, sty.frame46)}
            >
              <ItemTable
                data-plasmic-name={"itemTable"}
                data-plasmic-override={overrides.itemTable}
                className={classNames("__wab_instance", sty.itemTable)}
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "frame11",
    "frame14",
    "logo",
    "frame12",
    "menuItem2",
    "frame13",
    "frame6",
    "frame8",
    "frame10",
    "frame7",
    "vuesaxLinearLogout",
    "vuesaxLinearLogout2",
    "frame19",
    "frame20",
    "vuesaxLinearSearchNormal",
    "vuesaxLinearSearchNormal2",
    "frame18",
    "frame9",
    "vuesaxLinearAdd",
    "vuesaxLinearAdd2",
    "frame17",
    "frame16",
    "frame15",
    "vuesaxBoldArrowDown",
    "vuesaxBoldArrowDown2",
    "empty1",
    "frame21",
    "vuesaxLinearAdd3",
    "vuesaxLinearAdd4",
    "category",
    "frame47",
    "headerTable",
    "frame46",
    "itemTable"
  ],
  frame11: [
    "frame11",
    "frame14",
    "logo",
    "frame12",
    "menuItem2",
    "frame13",
    "frame6",
    "frame8",
    "frame10",
    "frame7",
    "vuesaxLinearLogout",
    "vuesaxLinearLogout2"
  ],
  frame14: ["frame14", "logo", "frame12", "menuItem2"],
  logo: ["logo"],
  frame12: ["frame12", "menuItem2"],
  menuItem2: ["menuItem2"],
  frame13: [
    "frame13",
    "frame6",
    "frame8",
    "frame10",
    "frame7",
    "vuesaxLinearLogout",
    "vuesaxLinearLogout2"
  ],
  frame6: ["frame6", "frame8"],
  frame8: ["frame8"],
  frame10: ["frame10", "frame7", "vuesaxLinearLogout", "vuesaxLinearLogout2"],
  frame7: ["frame7", "vuesaxLinearLogout", "vuesaxLinearLogout2"],
  vuesaxLinearLogout: ["vuesaxLinearLogout", "vuesaxLinearLogout2"],
  vuesaxLinearLogout2: ["vuesaxLinearLogout2"],
  frame19: [
    "frame19",
    "frame20",
    "vuesaxLinearSearchNormal",
    "vuesaxLinearSearchNormal2",
    "frame18",
    "frame9",
    "vuesaxLinearAdd",
    "vuesaxLinearAdd2",
    "frame17",
    "frame16",
    "frame15",
    "vuesaxBoldArrowDown",
    "vuesaxBoldArrowDown2"
  ],
  frame20: ["frame20", "vuesaxLinearSearchNormal", "vuesaxLinearSearchNormal2"],
  vuesaxLinearSearchNormal: [
    "vuesaxLinearSearchNormal",
    "vuesaxLinearSearchNormal2"
  ],
  vuesaxLinearSearchNormal2: ["vuesaxLinearSearchNormal2"],
  frame18: [
    "frame18",
    "frame9",
    "vuesaxLinearAdd",
    "vuesaxLinearAdd2",
    "frame17",
    "frame16",
    "frame15",
    "vuesaxBoldArrowDown",
    "vuesaxBoldArrowDown2"
  ],
  frame9: ["frame9", "vuesaxLinearAdd", "vuesaxLinearAdd2"],
  vuesaxLinearAdd: ["vuesaxLinearAdd", "vuesaxLinearAdd2"],
  vuesaxLinearAdd2: ["vuesaxLinearAdd2"],
  frame17: [
    "frame17",
    "frame16",
    "frame15",
    "vuesaxBoldArrowDown",
    "vuesaxBoldArrowDown2"
  ],
  frame16: [
    "frame16",
    "frame15",
    "vuesaxBoldArrowDown",
    "vuesaxBoldArrowDown2"
  ],
  frame15: ["frame15", "vuesaxBoldArrowDown", "vuesaxBoldArrowDown2"],
  vuesaxBoldArrowDown: ["vuesaxBoldArrowDown", "vuesaxBoldArrowDown2"],
  vuesaxBoldArrowDown2: ["vuesaxBoldArrowDown2"],
  empty1: ["empty1"],
  frame21: ["frame21", "vuesaxLinearAdd3", "vuesaxLinearAdd4"],
  vuesaxLinearAdd3: ["vuesaxLinearAdd3", "vuesaxLinearAdd4"],
  vuesaxLinearAdd4: ["vuesaxLinearAdd4"],
  category: ["category"],
  frame47: ["frame47", "headerTable", "frame46", "itemTable"],
  headerTable: ["headerTable"],
  frame46: ["frame46", "itemTable"],
  itemTable: ["itemTable"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  frame11: "div";
  frame14: "div";
  logo: "div";
  frame12: "div";
  menuItem2: typeof MenuItem2;
  frame13: "div";
  frame6: "div";
  frame8: "div";
  frame10: "div";
  frame7: "div";
  vuesaxLinearLogout: "div";
  vuesaxLinearLogout2: "div";
  frame19: "div";
  frame20: "div";
  vuesaxLinearSearchNormal: "div";
  vuesaxLinearSearchNormal2: "div";
  frame18: "div";
  frame9: "div";
  vuesaxLinearAdd: "div";
  vuesaxLinearAdd2: "div";
  frame17: "div";
  frame16: "div";
  frame15: "div";
  vuesaxBoldArrowDown: "div";
  vuesaxBoldArrowDown2: "div";
  empty1: "div";
  frame21: "div";
  vuesaxLinearAdd3: "div";
  vuesaxLinearAdd4: "div";
  category: typeof Category;
  frame47: "div";
  headerTable: typeof HeaderTable;
  frame46: "div";
  itemTable: typeof ItemTable;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSideBar__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSideBar__VariantsArgs;
    args?: PlasmicSideBar__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSideBar__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicSideBar__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSideBar__ArgProps,
          internalVariantPropNames: PlasmicSideBar__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSideBar__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSideBar";
  } else {
    func.displayName = `PlasmicSideBar.${nodeName}`;
  }
  return func;
}

export const PlasmicSideBar = Object.assign(
  // Top-level PlasmicSideBar renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    frame11: makeNodeComponent("frame11"),
    frame14: makeNodeComponent("frame14"),
    logo: makeNodeComponent("logo"),
    frame12: makeNodeComponent("frame12"),
    menuItem2: makeNodeComponent("menuItem2"),
    frame13: makeNodeComponent("frame13"),
    frame6: makeNodeComponent("frame6"),
    frame8: makeNodeComponent("frame8"),
    frame10: makeNodeComponent("frame10"),
    frame7: makeNodeComponent("frame7"),
    vuesaxLinearLogout: makeNodeComponent("vuesaxLinearLogout"),
    vuesaxLinearLogout2: makeNodeComponent("vuesaxLinearLogout2"),
    frame19: makeNodeComponent("frame19"),
    frame20: makeNodeComponent("frame20"),
    vuesaxLinearSearchNormal: makeNodeComponent("vuesaxLinearSearchNormal"),
    vuesaxLinearSearchNormal2: makeNodeComponent("vuesaxLinearSearchNormal2"),
    frame18: makeNodeComponent("frame18"),
    frame9: makeNodeComponent("frame9"),
    vuesaxLinearAdd: makeNodeComponent("vuesaxLinearAdd"),
    vuesaxLinearAdd2: makeNodeComponent("vuesaxLinearAdd2"),
    frame17: makeNodeComponent("frame17"),
    frame16: makeNodeComponent("frame16"),
    frame15: makeNodeComponent("frame15"),
    vuesaxBoldArrowDown: makeNodeComponent("vuesaxBoldArrowDown"),
    vuesaxBoldArrowDown2: makeNodeComponent("vuesaxBoldArrowDown2"),
    empty1: makeNodeComponent("empty1"),
    frame21: makeNodeComponent("frame21"),
    vuesaxLinearAdd3: makeNodeComponent("vuesaxLinearAdd3"),
    vuesaxLinearAdd4: makeNodeComponent("vuesaxLinearAdd4"),
    category: makeNodeComponent("category"),
    frame47: makeNodeComponent("frame47"),
    headerTable: makeNodeComponent("headerTable"),
    frame46: makeNodeComponent("frame46"),
    itemTable: makeNodeComponent("itemTable"),

    // Metadata about props expected for PlasmicSideBar
    internalVariantProps: PlasmicSideBar__VariantProps,
    internalArgProps: PlasmicSideBar__ArgProps
  }
);

export default PlasmicSideBar;
/* prettier-ignore-end */
