/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jNLLztuNGViHKFo35zGuKj

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsg7YyWqn5Z2Pk } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: G7yyWQN5Z2Pk/globalVariant
import { useScreenVariants as useScreenVariantsrf3U7XB0SO } from "../library_tabler_3_2_icons/PlasmicGlobalVariant__Screen"; // plasmic-import: Rf3u7x-B0S_o/globalVariant
import { useScreenVariants as useScreenVariantscqh1YWTrsJfR } from "../library_tailwind_3_4_color_tokens/PlasmicGlobalVariant__Screen"; // plasmic-import: CQH1yWTrsJfR/globalVariant
import { useScreenVariants as useScreenVariantssunYRowGfPxL } from "../library_tailwind_3_4_number_tokens/PlasmicGlobalVariant__Screen"; // plasmic-import: sunYRowGFPxL/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsg7YyWqn5Z2Pk,
  screen: useScreenVariantsrf3U7XB0SO,
  screen: useScreenVariantscqh1YWTrsJfR,
  screen: useScreenVariantssunYRowGfPxL
});
