/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jNLLztuNGViHKFo35zGuKj
// Component: kRWpDGSkUQ3q

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import PageLayout from "../../PageLayout"; // plasmic-import: R8ccW3HwabrW/component
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { RichList } from "@plasmicpkgs/plasmic-rich-components/skinny/rich-list";
import { RichTable } from "@plasmicpkgs/plasmic-rich-components/skinny/rich-table";
import { tableHelpers as RichTable_Helpers } from "@plasmicpkgs/plasmic-rich-components/skinny/rich-table";
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: jNLLztuNGViHKFo35zGuKj/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: jNLLztuNGViHKFo35zGuKj/styleTokensProvider
import { _useStyleTokens as useStyleTokens_antd_5_hostless } from "../antd_5_hostless/PlasmicStyleTokensProvider"; // plasmic-import: ohDidvG9XsCeFumugENU3J/styleTokensProvider
import { _useStyleTokens as useStyleTokens_plasmic_rich_components } from "../plasmic_rich_components/PlasmicStyleTokensProvider"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/styleTokensProvider
import { _useStyleTokens as useStyleTokens_library_tailwind_3_4_colors } from "../library_tailwind_3_4_color_tokens/PlasmicStyleTokensProvider"; // plasmic-import: 5ZtnypMovRHeeP3YTdPCYL/styleTokensProvider
import { _useStyleTokens as useStyleTokens_library_tailwind_3_4_number_tokens } from "../library_tailwind_3_4_number_tokens/PlasmicStyleTokensProvider"; // plasmic-import: 4vjRXvnb4XuY6J15w9oRcQ/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: jNLLztuNGViHKFo35zGuKj/projectcss
import sty from "./PlasmicPositions.module.css"; // plasmic-import: kRWpDGSkUQ3q/css

createPlasmicElementProxy;

export type PlasmicPositions__VariantMembers = {};
export type PlasmicPositions__VariantsArgs = {};
type VariantPropType = keyof PlasmicPositions__VariantsArgs;
export const PlasmicPositions__VariantProps = new Array<VariantPropType>();

export type PlasmicPositions__ArgsType = {};
type ArgPropType = keyof PlasmicPositions__ArgsType;
export const PlasmicPositions__ArgProps = new Array<ArgPropType>();

export type PlasmicPositions__OverridesType = {
  root?: Flex__<"div">;
  pageLayout?: Flex__<typeof PageLayout>;
  section?: Flex__<"section">;
  dataList?: Flex__<typeof RichList>;
  positions?: Flex__<typeof RichTable>;
};

export interface DefaultPositionsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPositions__RenderFunc(props: {
  variants: PlasmicPositions__VariantsArgs;
  args: PlasmicPositions__ArgsType;
  overrides: PlasmicPositions__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const currentUser = useCurrentUser?.() || {};

  let [$queries, setDollarQueries] = React.useState<
    Record<string, ReturnType<typeof usePlasmicDataOp>>
  >({});
  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "positions.selectedRowKey",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("selectedRowKey", RichTable_Helpers)
      },
      {
        path: "positions.selectedRow",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("selectedRow", RichTable_Helpers)
      },
      {
        path: "positions.selectedRows",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("selectedRows", RichTable_Helpers)
      },
      {
        path: "positions.selectedRowKeys",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("selectedRowKeys", RichTable_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $refs
  });
  const dataSourcesCtx = usePlasmicDataSourceContext();
  const plasmicInvalidate = usePlasmicInvalidate();

  const new$Queries: Record<string, ReturnType<typeof usePlasmicDataOp>> = {
    positions: usePlasmicDataOp(() => {
      return {
        sourceId: "9Hyr6o3HvJqQjfb3ajKmSt",
        opId: "cff7c7a7-3079-43e0-9ea5-7b1526c56218",
        userArgs: {},
        cacheKey: `plasmic.$.cff7c7a7-3079-43e0-9ea5-7b1526c56218.$.`,
        invalidatedKeys: null,
        roleId: "605ad21c-f9ec-4b20-8250-03d19c976d46"
      };
    }),
    depts: usePlasmicDataOp(() => {
      return {
        sourceId: "9Hyr6o3HvJqQjfb3ajKmSt",
        opId: "5679b9cd-3afc-4d5c-9a31-46f6f4fad557",
        userArgs: {},
        cacheKey: `plasmic.$.5679b9cd-3afc-4d5c-9a31-46f6f4fad557.$.`,
        invalidatedKeys: null,
        roleId: "605ad21c-f9ec-4b20-8250-03d19c976d46"
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);

    $queries = new$Queries;
  }

  const styleTokensClassNames = _useStyleTokens();
  const styleTokensClassNames_antd_5_hostless =
    useStyleTokens_antd_5_hostless();
  const styleTokensClassNames_plasmic_rich_components =
    useStyleTokens_plasmic_rich_components();
  const styleTokensClassNames_library_tailwind_3_4_colors =
    useStyleTokens_library_tailwind_3_4_colors();
  const styleTokensClassNames_library_tailwind_3_4_number_tokens =
    useStyleTokens_library_tailwind_3_4_number_tokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            styleTokensClassNames_antd_5_hostless,
            styleTokensClassNames_plasmic_rich_components,
            styleTokensClassNames_library_tailwind_3_4_colors,
            styleTokensClassNames_library_tailwind_3_4_number_tokens,
            sty.root
          )}
        >
          <PageLayout
            data-plasmic-name={"pageLayout"}
            data-plasmic-override={overrides.pageLayout}
            className={classNames("__wab_instance", sty.pageLayout)}
          >
            <DataCtxReader__>
              {$ctx => (
                <section
                  data-plasmic-name={"section"}
                  data-plasmic-override={overrides.section}
                  className={classNames(projectcss.all, sty.section)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__foKzZ)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___4CsRu
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__c5I3B
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__bpCrk
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__zLtdg
                            )}
                          >
                            {"Departments"}
                          </h4>
                          <p
                            className={classNames(
                              projectcss.all,
                              projectcss.p,
                              projectcss.__wab_text,
                              sty.p___78M4D
                            )}
                          >
                            {
                              "There are two queries on this page. One is for depts, and the other is for positions."
                            }
                          </p>
                        </div>
                        <AntdButton
                          className={classNames(
                            "__wab_instance",
                            sty.button__zz8Hm
                          )}
                          href={`/new-department`}
                          size={"large"}
                          type={"primary"}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___0UBP
                            )}
                          >
                            {"Add a dept"}
                          </div>
                        </AntdButton>
                      </div>
                      <RichList
                        data-plasmic-name={"dataList"}
                        data-plasmic-override={overrides.dataList}
                        bordered={true}
                        className={classNames("__wab_instance", sty.dataList)}
                        data={(() => {
                          try {
                            return $queries.depts;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()}
                        rowActions={(() => {
                          const __composite = [
                            { type: null, label: null, children: null }
                          ];
                          __composite["0"]["type"] = "menu";
                          __composite["0"]["label"] = "...";
                          __composite["0"]["children"] = (() => {
                            const __composite = [
                              { label: null, onClick: null }
                            ];
                            __composite["0"]["label"] = "Delete";
                            __composite["0"]["onClick"] = async (
                              rowKey,
                              row
                            ) => {
                              const $steps = {};

                              $steps["tutorialdbDeleteMany"] = true
                                ? (() => {
                                    const actionArgs = {
                                      dataOp: {
                                        sourceId: "9Hyr6o3HvJqQjfb3ajKmSt",
                                        opId: "19a8c6c4-877c-47bb-82a3-03039bf6efed",
                                        userArgs: {
                                          conditions: [row.id]
                                        },
                                        cacheKey: null,
                                        invalidatedKeys: [
                                          "plasmic_refresh_all"
                                        ],
                                        roleId: null
                                      }
                                    };
                                    return (async ({
                                      dataOp,
                                      continueOnError
                                    }) => {
                                      try {
                                        const response =
                                          await executePlasmicDataOp(dataOp, {
                                            userAuthToken:
                                              dataSourcesCtx?.userAuthToken,
                                            user: dataSourcesCtx?.user
                                          });
                                        await plasmicInvalidate(
                                          dataOp.invalidatedKeys
                                        );
                                        return response;
                                      } catch (e) {
                                        if (!continueOnError) {
                                          throw e;
                                        }
                                        return e;
                                      }
                                    })?.apply(null, [actionArgs]);
                                  })()
                                : undefined;
                              if (
                                $steps["tutorialdbDeleteMany"] != null &&
                                typeof $steps["tutorialdbDeleteMany"] ===
                                  "object" &&
                                typeof $steps["tutorialdbDeleteMany"].then ===
                                  "function"
                              ) {
                                $steps["tutorialdbDeleteMany"] = await $steps[
                                  "tutorialdbDeleteMany"
                                ];
                              }
                            };
                            return __composite;
                          })();
                          return __composite;
                        })()}
                        type={"grid"}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__mvgQf)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__qbXjn
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__nv1S7
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__h438C
                            )}
                          >
                            {"Jobs"}
                          </h4>
                          <p
                            className={classNames(
                              projectcss.all,
                              projectcss.p,
                              projectcss.__wab_text,
                              sty.p__eUDmp
                            )}
                          >
                            {
                              "View all job listings across your organization and their applicant numbers. This one uses a custom SQL query to also pull in the number of items."
                            }
                          </p>
                        </div>
                        <AntdButton
                          className={classNames(
                            "__wab_instance",
                            sty.button___3KRV
                          )}
                          href={`/new-position`}
                          size={"large"}
                          type={"primary"}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__mBxyF
                            )}
                          >
                            {"Add a job"}
                          </div>
                        </AntdButton>
                      </div>
                      {(() => {
                        const child$Props = {
                          canSelectRows: "click",
                          className: classNames(
                            "__wab_instance",
                            sty.positions
                          ),
                          data: (() => {
                            try {
                              return $queries.positions;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })(),
                          defaultSize: hasVariant(
                            globalVariants,
                            "screen",
                            "mobileOnly"
                          )
                            ? "small"
                            : undefined,
                          fields: (() => {
                            const __composite = [
                              { key: "id", fieldId: "id", isHidden: null },
                              { key: "title", fieldId: "title" },
                              {
                                key: "description",
                                fieldId: "description",
                                isHidden: null
                              },
                              {
                                key: "department_id",
                                fieldId: "department_id",
                                title: null,
                                isHidden: null
                              },
                              {
                                key: "archived",
                                fieldId: "archived",
                                isHidden: null
                              },
                              {
                                key: "created_at",
                                fieldId: "created_at",
                                isHidden: null
                              },
                              { key: "dept", fieldId: "dept", title: null },
                              {
                                key: "num_candidates",
                                fieldId: "num_candidates",
                                isHidden: null
                              },
                              {
                                key: "num_active_candidates",
                                fieldId: "num_active_candidates",
                                title: null
                              }
                            ];
                            __composite["0"]["isHidden"] = true;
                            __composite["2"]["isHidden"] = true;
                            __composite["3"]["title"] = "dept";
                            __composite["3"]["isHidden"] = true;
                            __composite["4"]["isHidden"] = true;
                            __composite["5"]["isHidden"] = true;
                            __composite["6"]["title"] = "Dept";
                            __composite["7"]["isHidden"] = true;
                            __composite["8"]["title"] = "Active Candidates";
                            return __composite;
                          })(),

                          onRowClick: async (rowKey, row, event) => {
                            const $steps = {};

                            $steps["goToPosition"] = true
                              ? (() => {
                                  const actionArgs = {
                                    destination: `/position/${(() => {
                                      try {
                                        return row.id;
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return undefined;
                                        }
                                        throw e;
                                      }
                                    })()}`
                                  };
                                  return (({ destination }) => {
                                    if (
                                      typeof destination === "string" &&
                                      destination.startsWith("#")
                                    ) {
                                      document
                                        .getElementById(destination.substr(1))
                                        .scrollIntoView({ behavior: "smooth" });
                                    } else {
                                      __nextRouter?.push(destination);
                                    }
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                            if (
                              $steps["goToPosition"] != null &&
                              typeof $steps["goToPosition"] === "object" &&
                              typeof $steps["goToPosition"].then === "function"
                            ) {
                              $steps["goToPosition"] = await $steps[
                                "goToPosition"
                              ];
                            }
                          },
                          onRowSelectionChanged: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "selectedRowKey",
                              ["positions", "selectedRowKey"],
                              RichTable_Helpers
                            ).apply(null, eventArgs);
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "selectedRow",
                              ["positions", "selectedRow"],
                              RichTable_Helpers
                            ).apply(null, eventArgs);
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "selectedRows",
                              ["positions", "selectedRows"],
                              RichTable_Helpers
                            ).apply(null, eventArgs);
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "selectedRowKeys",
                              ["positions", "selectedRowKeys"],
                              RichTable_Helpers
                            ).apply(null, eventArgs);
                          },
                          pageSize: 20,
                          scopeClassName: sty["positions__instance"],
                          selectedRowKey: generateStateValueProp($state, [
                            "positions",
                            "selectedRowKey"
                          ]),
                          selectedRowKeys: generateStateValueProp($state, [
                            "positions",
                            "selectedRowKeys"
                          ]),
                          themeResetClassName: classNames(
                            projectcss.root_reset,
                            projectcss.root_reset_tags,
                            projectcss.plasmic_default_styles,
                            projectcss.plasmic_mixins,
                            styleTokensClassNames,
                            styleTokensClassNames_antd_5_hostless,
                            styleTokensClassNames_plasmic_rich_components,
                            styleTokensClassNames_library_tailwind_3_4_colors,
                            styleTokensClassNames_library_tailwind_3_4_number_tokens
                          )
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "selectedRowKey",
                              plasmicStateName: "positions.selectedRowKey"
                            },
                            {
                              name: "selectedRow",
                              plasmicStateName: "positions.selectedRow"
                            },
                            {
                              name: "selectedRows",
                              plasmicStateName: "positions.selectedRows"
                            },
                            {
                              name: "selectedRowKeys",
                              plasmicStateName: "positions.selectedRowKeys"
                            }
                          ],
                          [],
                          RichTable_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <RichTable
                            data-plasmic-name={"positions"}
                            data-plasmic-override={overrides.positions}
                            {...child$Props}
                          />
                        );
                      })()}
                    </div>
                  </div>
                </section>
              )}
            </DataCtxReader__>
          </PageLayout>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "pageLayout", "section", "dataList", "positions"],
  pageLayout: ["pageLayout", "section", "dataList", "positions"],
  section: ["section", "dataList", "positions"],
  dataList: ["dataList"],
  positions: ["positions"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  pageLayout: typeof PageLayout;
  section: "section";
  dataList: typeof RichList;
  positions: typeof RichTable;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPositions__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPositions__VariantsArgs;
    args?: PlasmicPositions__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPositions__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPositions__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPositions__ArgProps,
          internalVariantPropNames: PlasmicPositions__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPositions__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPositions";
  } else {
    func.displayName = `PlasmicPositions.${nodeName}`;
  }
  return func;
}

function withPlasmicPageGuard<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const PageGuard: React.FC<P> = props => (
    <PlasmicPageGuard__
      minRole={"605ad21c-f9ec-4b20-8250-03d19c976d46"}
      appId={"jNLLztuNGViHKFo35zGuKj"}
      authorizeEndpoint={"https://studio.plasmic.app/authorize"}
      canTriggerLogin={true}
    >
      <WrappedComponent {...props} />
    </PlasmicPageGuard__>
  );

  return PageGuard;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "jNLLztuNGViHKFo35zGuKj"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicPositions = Object.assign(
  // Top-level PlasmicPositions renders the root element
  withUsePlasmicAuth(withPlasmicPageGuard(makeNodeComponent("root"))),
  {
    // Helper components rendering sub-elements
    pageLayout: makeNodeComponent("pageLayout"),
    section: makeNodeComponent("section"),
    dataList: makeNodeComponent("dataList"),
    positions: makeNodeComponent("positions"),

    // Metadata about props expected for PlasmicPositions
    internalVariantProps: PlasmicPositions__VariantProps,
    internalArgProps: PlasmicPositions__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicPositions;
/* prettier-ignore-end */
